[package]
name = "testcrate"
version = "0.1.0"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]

[features]
lua54 = []
lua53 = []
lua52 = []
lua51 = []
std = []
default = ["std"]

[build-dependencies.lua-src]
path = ".."
features = ["ucid"]
